import '../domain/entities/habit.dart';

class HabitTemplates {
  static const categoryNames = {
    HabitCategory.popular: 'Popular',
    HabitCategory.health: 'Salud',
    HabitCategory.sports: 'Deportes',
    HabitCategory.lifestyle: 'Estilo de vida',
    HabitCategory.time: 'Tiempo',
    HabitCategory.quit: 'Dejar',
  };

  static const categoryIcons = {
    HabitCategory.popular: 'HOT',
    HabitCategory.health: '♥',
    HabitCategory.sports: 'RUN',
    HabitCategory.lifestyle: 'HOME',
    HabitCategory.time: 'TIME',
    HabitCategory.quit: 'NO',
  };

  static const templates = [
    HabitTemplate(
      id: 'walk',
      name: 'Caminar',
      emoji: '🚶',
      category: HabitCategory.health,
      goalType: HabitGoalType.build,
      unit: 'pasos',
      defaultTarget: 10000,
      description: 'Completa pasos diarios para moverte mas.',
      ideas: ['Empieza con 10 minutos', 'Camina despues de comer'],
    ),
    HabitTemplate(
      id: 'sleep',
      name: 'Dormir',
      emoji: '🛏️',
      category: HabitCategory.health,
      goalType: HabitGoalType.build,
      unit: 'horas',
      defaultTarget: 8,
      description: 'Cuida tu descanso y energia diaria.',
      ideas: ['Rutina antes de dormir', 'Evita pantalla 30 minutos antes'],
    ),
    HabitTemplate(
      id: 'water',
      name: 'Beber agua',
      emoji: '💧',
      category: HabitCategory.health,
      goalType: HabitGoalType.counter,
      unit: 'vasos',
      defaultTarget: 8,
      description: 'Registra vasos de agua durante el dia.',
      ideas: ['Un vaso al despertar', 'Ten una botella visible'],
    ),
    HabitTemplate(
      id: 'meditation',
      name: 'Meditacion',
      emoji: '🧘',
      category: HabitCategory.health,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 10,
      description: 'Respira y baja revoluciones.',
      ideas: ['Prueba 2 minutos', 'Usa respiracion 4-7-8'],
    ),
    HabitTemplate(
      id: 'run',
      name: 'Correr',
      emoji: '🏃',
      category: HabitCategory.sports,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 30,
      description: 'Entrena por tiempo y guarda la sesion.',
      ideas: ['Corre suave', 'Alterna caminar y correr'],
    ),
    HabitTemplate(
      id: 'stretch',
      name: 'Estiramiento',
      emoji: '🙆',
      category: HabitCategory.sports,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 10,
      description: 'Recupera movilidad y reduce tension.',
      ideas: ['Cuello y espalda', 'Despues de trabajar'],
    ),
    HabitTemplate(
      id: 'cycling',
      name: 'Ciclismo',
      emoji: '🚴',
      category: HabitCategory.sports,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 45,
      description: 'Suma tiempo activo en bicicleta.',
    ),
    HabitTemplate(
      id: 'exercise',
      name: 'Ejercicio',
      emoji: '🏃',
      category: HabitCategory.sports,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 30,
      description: 'Haz cualquier actividad fisica.',
    ),
    HabitTemplate(
      id: 'read',
      name: 'Leer',
      emoji: '📚',
      category: HabitCategory.lifestyle,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 20,
      description: 'Tiempo de lectura sin distracciones.',
    ),
    HabitTemplate(
      id: 'journal',
      name: 'Escribir diario',
      emoji: '📝',
      category: HabitCategory.lifestyle,
      goalType: HabitGoalType.checklist,
      unit: 'dia',
      defaultTarget: 1,
      description: 'Cierra el dia con una reflexion corta.',
    ),
    HabitTemplate(
      id: 'clean',
      name: 'Ordenar casa',
      emoji: '🧹',
      category: HabitCategory.lifestyle,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 15,
      description: 'Pequenas sesiones para mantener orden.',
    ),
    HabitTemplate(
      id: 'focus',
      name: 'Trabajo profundo',
      emoji: '🎯',
      category: HabitCategory.time,
      goalType: HabitGoalType.timer,
      unit: 'min',
      defaultTarget: 50,
      description: 'Bloque sin interrupciones.',
    ),
    HabitTemplate(
      id: 'less_screen',
      name: 'Menos pantalla',
      emoji: '📵',
      category: HabitCategory.time,
      goalType: HabitGoalType.limit,
      unit: 'min',
      defaultTarget: 90,
      description: 'Define un maximo diario de pantalla recreativa.',
    ),
    HabitTemplate(
      id: 'less_games',
      name: 'Jugar Menos Juegos',
      emoji: '🎮',
      category: HabitCategory.quit,
      goalType: HabitGoalType.limit,
      unit: 'min',
      defaultTarget: 30,
      description: 'Temporizador con limite diario para videojuegos.',
      ideas: ['Juega despues de tareas', 'Cierra con alarma visible'],
    ),
    HabitTemplate(
      id: 'less_sugar',
      name: 'Comer Menos Azucar',
      emoji: '🍬',
      category: HabitCategory.quit,
      goalType: HabitGoalType.reduce,
      unit: 'porciones',
      defaultTarget: 1,
      description: 'Cuenta porciones y evita pasarte del acuerdo.',
      ideas: ['Cambia por fruta', 'No compres dulces grandes'],
    ),
    HabitTemplate(
      id: 'less_caffeine',
      name: 'Beber menos cafeina',
      emoji: '☕',
      category: HabitCategory.quit,
      goalType: HabitGoalType.reduce,
      unit: 'tazas',
      defaultTarget: 2,
      description: 'Controla cafe, energia y refrescos con cafeina.',
    ),
    HabitTemplate(
      id: 'less_alcohol',
      name: 'Beber menos alcohol',
      emoji: '🍺',
      category: HabitCategory.quit,
      goalType: HabitGoalType.reduce,
      unit: 'bebidas',
      defaultTarget: 0,
      description: 'Suma cada bebida y recibe ayuda si pasas tu limite.',
      ideas: ['Alterna con agua', 'Evita comprar de mas'],
    ),
    HabitTemplate(
      id: 'less_smoking',
      name: 'Fumar menos',
      emoji: '🚭',
      category: HabitCategory.quit,
      goalType: HabitGoalType.reduce,
      unit: 'cigarrillos',
      defaultTarget: 0,
      description: 'Registra consumos y reduce gradualmente.',
      ideas: ['Retrasa 10 minutos', 'Cambia por respirar profundo'],
    ),
    HabitTemplate(
      id: 'less_tv',
      name: 'Ver Menos TV',
      emoji: '📺',
      category: HabitCategory.quit,
      goalType: HabitGoalType.limit,
      unit: 'min',
      defaultTarget: 60,
      description: 'Temporizador de entretenimiento.',
    ),
    HabitTemplate(
      id: 'less_complain',
      name: 'Quejarse Menos',
      emoji: '😤',
      category: HabitCategory.quit,
      goalType: HabitGoalType.reduce,
      unit: 'veces',
      defaultTarget: 2,
      description: 'Cuenta impulsos y practica reformular.',
    ),
  ];

  static List<HabitTemplate> byCategory(HabitCategory category) {
    if (category == HabitCategory.popular) {
      return [
        templateById('walk'),
        templateById('sleep'),
        templateById('water'),
        templateById('exercise'),
        templateById('meditation'),
        templateById('less_screen'),
        templateById('less_sugar'),
        templateById('less_smoking'),
        templateById('less_games'),
      ];
    }
    return templates.where((habit) => habit.category == category).toList();
  }

  static HabitTemplate templateById(String id) {
    return templates.firstWhere(
      (habit) => habit.id == id,
      orElse: () => templates.first,
    );
  }
}
